version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env

  celery-worker:
    build: .
    command: celery -A bettingSystemProject worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A bettingSystemProject beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"