FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["celery", "-A", "bettingSystemProject", "worker", "--loglevel=debug", "--uid nobody", "--concurrency=2"]