# Generated by Django 6.0.2 on 2026-03-03 18:57

import bettingApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingApp', '0002_bet_event_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='expires_at',
            field=models.DateTimeField(default=bettingApp.models.default_expiry),
        ),
        migrations.AddField(
            model_name='bet',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(default=bettingApp.models.default_expiry),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(default=bettingApp.models.default_start),
        ),
        migrations.AddField(
            model_name='market',
            name='result',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
