# Generated by Django 6.0.2 on 2026-03-03 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingApp', '0003_bet_expires_at_bet_settled_event_ends_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='bettingApp.event'),
        ),
    ]
