# Generated by Django 6.0.2 on 2026-03-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettingApp', '0004_alter_market_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
