# Generated by Django 6.0.2 on 2026-03-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettingApp', '0005_alter_bet_expires_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='betrs_lost',
            new_name='bets_lost',
        ),
    ]
